# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-desafio' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-desafio
  pod 'Alamofire'

  target 'ios-desafioTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ios-desafioUITests' do
    # Pods for testing
  end

end
